config/routes.rb
Treebook::Application.routes.draw do
  devise_for :users #, controllers: {registrations: "users/registrations"}
  resources :statuses
  root to: 'statuses#index'
  resources :users
  resources :home

end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
	#accepts_nested_attributes_for :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attr_accessible :email, :password, :password_confirmation,
  #                 :first_name, :last_name, :profile, :remember_me


  has_many :statuses,
    dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :profile, presence: true,
  #    uniqueness: true,
  #    format: {
  #       with: /a-zA-Z0-9/,
  #       message: 'Must be formated correctly.'
  #    }
  def show_contact
    first_name + " " + last_name + " " + email + " " + phone_number.to_s +  twitter_handle + preferred_contact
  end


  def full_name
    first_name + " " + last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :configure_permitted_parameters, if: :devise_controller?




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :phone_number, :twitter_handle, :preferred_contact, :last_name, :profile, :email, :password, :password_confirmation)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :can_change, only: [:edit, :update, :destory]
  before_action :authenticate_user!

  # def full_name
  #   name= first_name + ' ' + last_name
  #   return name
  # end
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # def first_name
  #   @status.first_name
  # end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)
    @status.user = current_user

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    def can_change
      if @status.user != current_user
        redirect_to @status
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit( :user, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
# def set_current_user
#       @user = current_user
# end

 before_action :authenticate_user!

def index
    @users = User.all
end

# def show
#   @users = User.find(params[:id])
# end

# def set_user
#   @user = User.find(params[:id])
# end

private

  #params.permit(:user).permit(:user_id, :first_name, :phone_number, :twitter_handle, :preferred_contact, :last_name, :profile, :email)

end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type

		 when :alert
		 	"alert-danger"
		 when :notice		 	
			"alert-success"
		else
			""			

		 end 
	end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SatCom</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-inverse navbar-fixed-top " role="navigation">
			<div class= "container-fluid">

			 <div class="navbar-header">
			 	  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

				<a class="navbar-brand" style="color:#ed197b;">SatCom</a>
			</div>
			 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-left">
						<li><%= link_to "All statuses", statuses_path %></li>
						<li><%= link_to "All users", users_path %></li>
					</ul>

				<ul class = "nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li> <%= link_to current_user.full_name, edit_user_registration_path %></li>
						<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li> <%= link_to "Register", new_user_registration_path %></li>
						<li> <%= link_to "Log In", new_user_session_path %></li>
					<% end %>
				</ul>
			</div>

		</div>
			<div class="pink_me">
			</div>
	</div>

	<div class="container" id="bodytag">
	<% flash.each do |type, message| %>
		<div class="alert alert-dismissable <%= flash_class type %>">
		  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		  <%= message %>
		</div>
	<% end %>



		<%= yield %>



	</div>
</body>
</html>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-vertical"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
<div class="col-sm-3 well">
    <%= f.hidden_field :user_id, collection: User.all, label_method: :full_name %>

    <%= f.input :content %>

  <div class="form-actions btn btn-success">
    <%= f.submit  %>
  </div>
</div>
 </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1> All of the status</h1>
</div>
<div class="row">
  <div class= "col-sm-7">
    <%= link_to "Post a new status", new_status_path, class:"btn btn-success" %>



    <% @statuses.each do |status| %>
      <div class="status">

        <strong>  <%= status.user.full_name %> </strong>

        <p><%= status.content %> </p>

        <div class="meta">
          <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
          <span class="admin">
            | <%= link_to "Edit", edit_status_path(status) %> |
          </span>
        </div>

      </div>
    <% end %>
  </div>
  <div class="col-sm-5">
<span style="display: block !important; width: 320px; text-align: center; font-family: sans-serif; font-size: 12px;"><a href="http://www.wunderground.com/cgi-bin/findweather/getForecast?query=zmw:02101.1.99999&bannertypeclick=wu_clean2day" title="Boston, Massachusetts Weather Forecast" target="_blank"><img src="http://weathersticker.wunderground.com/weathersticker/cgi-bin/banner/ban/wxBanner?bannertype=wu_clean2day_cond&airportcode=KBOS&ForcedCity=Boston&ForcedState=MA&zip=02101&language=EN" alt="Find more about Weather in Boston, MA" width="300" /></a><br><a href="http://www.wunderground.com/cgi-bin/findweather/getForecast?query=zmw:02101.1.99999&bannertypeclick=wu_clean2day" title="Get latest Weather Forecast updates" style="font-family: sans-serif; font-size: 12px" target="_blank">Click for weather forecast</a></span>


<iframe src="http://www.google.com/uds/modules/elements/newsshow/iframe.html?q=boston%20tech&format=300x250"
        frameborder="0" width="300" height="250"
        marginwidth="0" marginheight="0">
</iframe>

<style type='text/css'>#indJobContent{padding-bottom: 5px;}#indJobContent .company_location{font-size: 11px;overflow: hidden;display:block;}#indJobContent.wide .job{display:block;float:left;margin-right: 5px;width: 135px;overflow: hidden}#indeed_widget_wrapper{position: relative;font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif;font-size: 13px;font-weight: normal;line-height: 18px;padding: 10px;height: auto;overflow: hidden;}#indeed_widget_header{font-size:18px; padding-bottom: 5px; }#indeed_search_wrapper{clear: both;font-size: 12px;margin-top: 0px;padding-top: 2px;}#indeed_search_wrapper label{font-size: 12px;line-height: inherit;text-align: left; margin-right: 5px;}#indeed_search_wrapper input[type='text']{width: 100px; font-size: 11px; }#indeed_search_wrapper #qc{float:left;}#indeed_search_wrapper #lc{float:right;}#indeed_search_wrapper.stacked #qc, #indeed_search_wrapper.stacked #lc{float: none; clear: both;}#indeed_search_wrapper.stacked input[type='text']{width: 150px;}#indeed_search_wrapper.stacked label{display: block;padding-bottom: 5px;}#indeed_search_footer{width:295px; padding-top: 5px; clear: both;}#indeed_link{position: absolute;bottom: 1px;right: 5px;clear: both;font-size: 11px; }#indeed_link a{text-decoration: none;}#results .job{padding: 1px 0px;}#pagination { clear: both; }</style><style type='text/css'>
#indeed_widget_wrapper{ width: 300px; height: 250px; background: #FFFFFF;}
#indeed_widget_wrapper{ border: 1px solid #DDDDDD; }
#indeed_widget_wrapper, #indeed_link a{ color: #000000;}
#indJobContent, #indeed_search_wrapper{ border-top: 1px solid #DDDDDD; }
#indJobContent a { color: #00c; }
#indeed_widget_header{ color: #000000; }
</style>
<script type='text/javascript'>
var ind_pub = '1439892112925001';
var ind_el = 'indJobContent';
var ind_pf = '';
var ind_q = 'Ruby';
var ind_l = 'Boston, Ma';
var ind_chnl = 'none';
var ind_n = 4;
var ind_d = 'http://www.indeed.com';
var ind_t = 40;
var ind_c = 30;
var ind_pgn = 1;
var ind_pgnCnt = 5;
</script>
<script type='text/javascript' src='http://www.indeed.com/ads/jobroll-widget-v3.js'></script>
<div id='indeed_widget_wrapper' style=''>
<div id='indeed_widget_header'>Ruby Boston</div>

<div id='indJobContent' class=""></div>

<div id='indeed_search_wrapper'>
<script type='text/javascript'>
function clearDefaults(){
var formInputs=document.getElementById('indeed_jobform').elements;
for(var i=0;i<formInputs.length;i++){
if(formInputs[i].value=='title, keywords' || formInputs[i].value=='city, state, or zip'){
formInputs[i].value='';
}
}
}
</script>
<form onsubmit='clearDefaults();' method='get' action='http://www.indeed.com/jobs' id='indeed_jobform' target="_new">
<div id="qc"><label>What:</label><input type='text' onfocus='this.value=""' value='title, keywords' name='q' id='q'></div>
<div id="lc"><label>Where:</label><input type='text' onfocus='this.value=""' value='city, state, or zip' name='l' id='l'></div>
<div id='indeed_search_footer'>
<div style='float:left'><input type='submit' value='Find Jobs' class='findjobs'></div>
</div>
<input type='hidden' name='indpubnum' id='indpubnum' value='1439892112925001'>
</form>
</div>

<div id='indeed_link'>
<a title="Job Search" href="http://www.indeed.com/" target="_new">jobs by <img alt=Indeed src='http://www.indeed.com/p/jobsearch.gif' style='border: 0;vertical-align: bottom;'>
</a>
</div>
</div>

  </div>

</div>

app/views/statuses/new.html.erb
<body>
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>
</bdoy>

app/views/statuses/show.html.erb
<div class= "row">
<div class= "col-md-10">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
  </p>

<p>
  <strong>Content:</strong>
 <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

</div>
<div class= "col-md-2">
<span style="display: block !important; width: 320px; text-align: center; font-family: sans-serif; font-size: 12px;"><a href="http://www.wunderground.com/cgi-bin/findweather/getForecast?query=zmw:02101.1.99999&bannertypeclick=wu_clean2day" title="Boston, Massachusetts Weather Forecast" target="_blank"><img src="http://weathersticker.wunderground.com/weathersticker/cgi-bin/banner/ban/wxBanner?bannertype=wu_clean2day_cond&airportcode=KBOS&ForcedCity=Boston&ForcedState=MA&zip=02101&language=EN" alt="Find more about Weather in Boston, MA" width="300" /></a><br><a href="http://www.wunderground.com/cgi-bin/findweather/getForecast?query=zmw:02101.1.99999&bannertypeclick=wu_clean2day" title="Get latest Weather Forecast updates" style="font-family: sans-serif; font-size: 12px" target="_blank">Click for weather forecast</a></span>
</div>
</div>

app/views/users/index.html.erb
<h1> Here are all the users: </h1>
<table class="table table-hover">
<thead>
<tr>
<th> Name
</th>
<th> Phone Number
</th>
<th> Email
</th>
<th> Twitter
</th>
<th> Preferred Contact
</th>
</tr>
</thead>
<% @users.each do |user| %>

<tbody>

  <td>
    <%= user.full_name  %>
  </td>

  <td>
    <%= user.phone_number %>
  </td>

  <td>
    <%= user.email %>
  </td>
    <td>
    <%= user.twitter_handle %>
  </td>

  </td>
    <td>
    <%= user.preferred_contact %>
  </td>

</tbody>



<% end %>
</table>